# Generated by Django 4.2.7 on 2024-02-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cacti', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
