# Generated by Django 4.2.7 on 2024-03-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cacti', '0004_profile_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
